set_datetime:
  name: Set Chore Datetime
  description: Set a datetime field on a Chore device
  fields:
    entity_id:
      name: Target Datetime
      description: Pick a datetime entity (Next Due Date or Last Done Date)
      required: true
      selector:
        entity:
          domain: datetime
    value:
      name: New Date/Time
      description: The datetime to set
      required: true
      selector:
        datetime: {}
