set_value:
  name: Set Value
  description: Set a field on a Chore or Score device
  fields:
    field:
      description: Field name (e.g. days, points, last_done_by)
      example: points
    value:
      description: Value to set
      example: 5

set_datetime:
  name: Set Datetime
  description: Set a datetime field on a Chore device
  fields:
    field:
      description: Datetime field (last_done_date or next_due_date)
      example: next_due_date
    value:
      description: Datetime in ISO 8601 format
      example: "2025-10-01T15:00:00"

complete_chore:
  name: Complete Chore
  description: Marks a chore as completed, updates last and next dates
  fields: {}
